{% set name = "pyglpk" %}
{% set version = "0.4.8" %}
{% set source = "glpk" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ source[0] }}/{{ source }}/{{ source }}-{{ version }}.tar.gz
  sha256: 419091b0dbbb061c83c64be2e038d1f29182b986627f8f8c4971601e17fbd013

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - glpk
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - python
    - glpk

test:
  imports:
    - glpk
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://tfinley.net/software/pyglpk/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Bradford Boyles fork of Thoams Finlays pyglpk package. This is compatible with python-3
  description: |
    Thomas Finlay wrote the original pyglpk package, and Bradford Boyle updated it to python 2.7 and then
    python 3. This installation is based on the pypi package and is maintained by @linsalrob
  doc_url: http://tfinley.net/software/pyglpk/
  dev_url: https://github.com/bradfordboyle/pyglpk

extra:
  recipe-maintainers:
    - linsalrob
